
--## MAIN MENU
INSERT INTO MENUMAS (MENUCD, MENUNM, MENUGROUP, INSERTABLE, UPDATEABLE, DELETEABLE, ORDMENU, ORDGROUP, EDATE, EUSER, WEBMENU, PAGENM, MENUNM_LABEL)
VALUES ('MENU.A', 'MASTER', 'MENU', 'Y', 'Y', 'Y', 'A', 1, SYSDATE, 'PARESH', NULL, NULL, NULL);

INSERT INTO MENUMAS (MENUCD, MENUNM, MENUGROUP, INSERTABLE, UPDATEABLE, DELETEABLE, ORDMENU, ORDGROUP, EDATE, EUSER, WEBMENU, PAGENM, MENUNM_LABEL)
VALUES ('MENU.B', 'TRANSACTION', 'MENU', 'Y', 'Y', 'Y', 'B', 2, SYSDATE, 'PARESH', NULL, NULL, NULL);

INSERT INTO MENUMAS (MENUCD, MENUNM, MENUGROUP, INSERTABLE, UPDATEABLE, DELETEABLE, ORDMENU, ORDGROUP, EDATE, EUSER, WEBMENU, PAGENM, MENUNM_LABEL)
VALUES ('MENU.C', 'REPORT', 'MENU', 'Y', 'Y', 'Y', 'C', 3, SYSDATE, 'PARESH', NULL, NULL, NULL);

--INCLUDED IN REPORT
--INSERT INTO MENUMAS (MENUCD, MENUNM, MENUGROUP, INSERTABLE, UPDATEABLE, DELETEABLE, ORDMENU, ORDGROUP, EDATE, EUSER, WEBMENU, PAGENM, MENUNM_LABEL)
--VALUES ('MENU.D', 'FORMS', 'MENU', 'Y', 'Y', 'Y', 'C', 4, SYSDATE, 'PARESH', NULL, NULL, NULL);

INSERT INTO MENUMAS (MENUCD, MENUNM, MENUGROUP, INSERTABLE, UPDATEABLE, DELETEABLE, ORDMENU, ORDGROUP, EDATE, EUSER, WEBMENU, PAGENM, MENUNM_LABEL)
VALUES ('MENU.F', 'UTILITY', 'MENU', 'Y', 'Y', 'Y', 'F', 6, SYSDATE, 'PARESH', NULL, NULL, NULL);


--## MASTER
INSERT INTO MENUMAS (MENUCD, MENUNM, MENUGROUP, INSERTABLE, UPDATEABLE, DELETEABLE, ORDMENU, ORDGROUP, EDATE, EUSER, WEBMENU, PAGENM, MENUNM_LABEL)
VALUES ('A.A01', 'COMPANY', 'MASTER', 'Y', 'Y', 'Y', 'A01', 1, SYSDATE, 'PARESH', NULL, NULL, NULL);

INSERT INTO MENUMAS (MENUCD, MENUNM, MENUGROUP, INSERTABLE, UPDATEABLE, DELETEABLE, ORDMENU, ORDGROUP, EDATE, EUSER, WEBMENU, PAGENM, MENUNM_LABEL)
VALUES ('A.A02', 'FINANCIAL YEAR', 'MASTER', 'Y', 'Y', 'Y', 'A02', 1, SYSDATE, 'PARESH', NULL, NULL, NULL);

INSERT INTO MENUMAS (MENUCD, MENUNM, MENUGROUP, INSERTABLE, UPDATEABLE, DELETEABLE, ORDMENU, ORDGROUP, EDATE, EUSER, WEBMENU, PAGENM, MENUNM_LABEL)
VALUES ('A.A03', 'DEPARTMENT', 'MASTER', 'Y', 'Y', 'Y', 'A03', 1, SYSDATE, 'PARESH', NULL, NULL, NULL);

INSERT INTO MENUMAS (MENUCD, MENUNM, MENUGROUP, INSERTABLE, UPDATEABLE, DELETEABLE, ORDMENU, ORDGROUP, EDATE, EUSER, WEBMENU, PAGENM, MENUNM_LABEL)
VALUES ('A.A04', 'DESIGNATION', 'MASTER', 'Y', 'Y', 'Y', 'A04', 1, SYSDATE, 'PARESH', NULL, NULL, NULL);

INSERT INTO MENUMAS (MENUCD, MENUNM, MENUGROUP, INSERTABLE, UPDATEABLE, DELETEABLE, ORDMENU, ORDGROUP, EDATE, EUSER, WEBMENU, PAGENM, MENUNM_LABEL)
VALUES ('A.A05', 'SALARY SLAB', 'MASTER', 'Y', 'Y', 'Y', 'A05', 1, SYSDATE, 'PARESH', NULL, NULL, NULL);

INSERT INTO MENUMAS (MENUCD, MENUNM, MENUGROUP, INSERTABLE, UPDATEABLE, DELETEABLE, ORDMENU, ORDGROUP, EDATE, EUSER, WEBMENU, PAGENM, MENUNM_LABEL)
VALUES ('A.A06', 'EMPLOYEE', 'MASTER', 'Y', 'Y', 'Y', 'A06', 1, SYSDATE, 'PARESH', NULL, NULL, NULL);

INSERT INTO MENUMAS (MENUCD, MENUNM, MENUGROUP, INSERTABLE, UPDATEABLE, DELETEABLE, ORDMENU, ORDGROUP, EDATE, EUSER, WEBMENU, PAGENM, MENUNM_LABEL)
VALUES ('A.A07', 'PT SLAB', 'MASTER', 'Y', 'Y', 'Y', 'A07', 1, SYSDATE, 'PARESH', NULL, NULL, NULL);

INSERT INTO MENUMAS (MENUCD, MENUNM, MENUGROUP, INSERTABLE, UPDATEABLE, DELETEABLE, ORDMENU, ORDGROUP, EDATE, EUSER, WEBMENU, PAGENM, MENUNM_LABEL)
VALUES ('A.A08', 'TA SLAB', 'MASTER', 'Y', 'Y', 'Y', 'A08', 1, SYSDATE, 'PARESH', NULL, NULL, NULL);

INSERT INTO MENUMAS (MENUCD, MENUNM, MENUGROUP, INSERTABLE, UPDATEABLE, DELETEABLE, ORDMENU, ORDGROUP, EDATE, EUSER, WEBMENU, PAGENM, MENUNM_LABEL)
VALUES ('A.A09', 'INCOME TAX SLAB', 'MASTER', 'Y', 'Y', 'Y', 'A09', 1, SYSDATE, 'PARESH', NULL, NULL, NULL);

INSERT INTO MENUMAS (MENUCD, MENUNM, MENUGROUP, INSERTABLE, UPDATEABLE, DELETEABLE, ORDMENU, ORDGROUP, EDATE, EUSER, WEBMENU, PAGENM, MENUNM_LABEL)
VALUES ('A.A10', 'FLOOR/DIVISION', 'MASTER', 'Y', 'Y', 'Y', 'A10', 1, SYSDATE, 'PARESH', NULL, NULL, NULL);


INSERT INTO MENUMAS (MENUCD, MENUNM, MENUGROUP, INSERTABLE, UPDATEABLE, DELETEABLE, ORDMENU, ORDGROUP, EDATE, EUSER, WEBMENU, PAGENM, MENUNM_LABEL)
VALUES ('A.A50', 'RULES', 'MASTER', 'Y', 'Y', 'Y', 'A50', 1, SYSDATE, 'PARESH', NULL, NULL, NULL);

INSERT INTO MENUMAS (MENUCD, MENUNM, MENUGROUP, INSERTABLE, UPDATEABLE, DELETEABLE, ORDMENU, ORDGROUP, EDATE, EUSER, WEBMENU, PAGENM, MENUNM_LABEL)
VALUES ('A.A51', 'USERS', 'MASTER', 'Y', 'Y', 'Y', 'A51', 1, SYSDATE, 'PARESH', NULL, NULL, NULL);

INSERT INTO MENUMAS (MENUCD, MENUNM, MENUGROUP, INSERTABLE, UPDATEABLE, DELETEABLE, ORDMENU, ORDGROUP, EDATE, EUSER, WEBMENU, PAGENM, MENUNM_LABEL)
VALUES ('A.A52', 'USER RIGHTS', 'MASTER', 'Y', 'Y', 'Y', 'A52', 1, SYSDATE, 'PARESH', NULL, NULL, NULL);



--## TRANSACTION

INSERT INTO MENUMAS (MENUCD, MENUNM, MENUGROUP, INSERTABLE, UPDATEABLE, DELETEABLE, ORDMENU, ORDGROUP, EDATE, EUSER, WEBMENU, PAGENM, MENUNM_LABEL)
VALUES ('B.B01', 'PAYROLL PROCESSING', 'TRANSACTION', 'Y', 'Y', 'Y', 'B01', 2, SYSDATE, 'PARESH', NULL, NULL, NULL);

INSERT INTO MENUMAS (MENUCD, MENUNM, MENUGROUP, INSERTABLE, UPDATEABLE, DELETEABLE, ORDMENU, ORDGROUP, EDATE, EUSER, WEBMENU, PAGENM, MENUNM_LABEL)
VALUES ('B.B02', 'SALARY', 'TRANSACTION', 'Y', 'Y', 'Y', 'B02', 2, SYSDATE, 'PARESH', NULL, NULL, NULL);

INSERT INTO MENUMAS (MENUCD, MENUNM, MENUGROUP, INSERTABLE, UPDATEABLE, DELETEABLE, ORDMENU, ORDGROUP, EDATE, EUSER, WEBMENU, PAGENM, MENUNM_LABEL)
VALUES ('B.B03', 'LEAVE', 'TRANSACTION', 'Y', 'Y', 'Y', 'B03', 2, SYSDATE, 'PARESH', NULL, NULL, NULL);

INSERT INTO MENUMAS (MENUCD, MENUNM, MENUGROUP, INSERTABLE, UPDATEABLE, DELETEABLE, ORDMENU, ORDGROUP, EDATE, EUSER, WEBMENU, PAGENM, MENUNM_LABEL)
VALUES ('B.B04', 'BONUS', 'TRANSACTION', 'Y', 'Y', 'Y', 'B04', 2, SYSDATE, 'PARESH', NULL, NULL, NULL);

INSERT INTO MENUMAS (MENUCD, MENUNM, MENUGROUP, INSERTABLE, UPDATEABLE, DELETEABLE, ORDMENU, ORDGROUP, EDATE, EUSER, WEBMENU, PAGENM, MENUNM_LABEL)
VALUES ('B.B05', 'FORM16', 'TRANSACTION', 'Y', 'Y', 'Y', 'B05', 2, SYSDATE, 'PARESH', NULL, NULL, NULL);


--## REPORTS

INSERT INTO MENUMAS (MENUCD, MENUNM, MENUGROUP, INSERTABLE, UPDATEABLE, DELETEABLE, ORDMENU, ORDGROUP, EDATE, EUSER, WEBMENU, PAGENM, MENUNM_LABEL)
VALUES ('C.C01', 'SALARY REGISTER', 'REPORT', 'N', 'N', 'N', 'C01', 3, SYSDATE, 'PARESH', NULL, NULL, NULL);

INSERT INTO MENUMAS (MENUCD, MENUNM, MENUGROUP, INSERTABLE, UPDATEABLE, DELETEABLE, ORDMENU, ORDGROUP, EDATE, EUSER, WEBMENU, PAGENM, MENUNM_LABEL)
VALUES ('C.C02', 'BONUS REGISTER', 'REPORT', 'N', 'N', 'N', 'C02', 3, SYSDATE, 'PARESH', NULL, NULL, NULL);

INSERT INTO MENUMAS (MENUCD, MENUNM, MENUGROUP, INSERTABLE, UPDATEABLE, DELETEABLE, ORDMENU, ORDGROUP, EDATE, EUSER, WEBMENU, PAGENM, MENUNM_LABEL)
VALUES ('C.C03', 'LEAVE REGISTER', 'REPORT', 'N', 'N', 'N', 'C03', 3, SYSDATE, 'PARESH', NULL, NULL, NULL);

INSERT INTO MENUMAS (MENUCD, MENUNM, MENUGROUP, INSERTABLE, UPDATEABLE, DELETEABLE, ORDMENU, ORDGROUP, EDATE, EUSER, WEBMENU, PAGENM, MENUNM_LABEL)
VALUES ('C.C04', 'PAYSLIP', 'REPORT', 'N', 'N', 'N', 'C04', 3, SYSDATE, 'PARESH', NULL, NULL, NULL);

INSERT INTO MENUMAS (MENUCD, MENUNM, MENUGROUP, INSERTABLE, UPDATEABLE, DELETEABLE, ORDMENU, ORDGROUP, EDATE, EUSER, WEBMENU, PAGENM, MENUNM_LABEL)
VALUES ('C.C05', 'PROFESSIONAL TAX', 'REPORT', 'N', 'N', 'N', 'C05', 3, SYSDATE, 'PARESH', NULL, NULL, NULL);

INSERT INTO MENUMAS (MENUCD, MENUNM, MENUGROUP, INSERTABLE, UPDATEABLE, DELETEABLE, ORDMENU, ORDGROUP, EDATE, EUSER, WEBMENU, PAGENM, MENUNM_LABEL)
VALUES ('C.C06', 'PROVIDENT FUND', 'REPORT', 'N', 'N', 'N', 'C06', 3, SYSDATE, 'PARESH', NULL, NULL, NULL);

INSERT INTO MENUMAS (MENUCD, MENUNM, MENUGROUP, INSERTABLE, UPDATEABLE, DELETEABLE, ORDMENU, ORDGROUP, EDATE, EUSER, WEBMENU, PAGENM, MENUNM_LABEL)
VALUES ('C.C07', 'ESIC', 'REPORT', 'N', 'N', 'N', 'C07', 3, SYSDATE, 'PARESH', NULL, NULL, NULL);

INSERT INTO MENUMAS (MENUCD, MENUNM, MENUGROUP, INSERTABLE, UPDATEABLE, DELETEABLE, ORDMENU, ORDGROUP, EDATE, EUSER, WEBMENU, PAGENM, MENUNM_LABEL)
VALUES ('C.C08', 'SALARY CERTIFICATE', 'REPORT', 'N', 'N', 'N', 'C08', 3, SYSDATE, 'PARESH', NULL, NULL, NULL);

--## FORMS
INSERT INTO MENUMAS (MENUCD, MENUNM, MENUGROUP, INSERTABLE, UPDATEABLE, DELETEABLE, ORDMENU, ORDGROUP, EDATE, EUSER, WEBMENU, PAGENM, MENUNM_LABEL)
VALUES ('C.C09', 'FORM NO. 16', 'REPORT', 'N', 'N', 'N', 'C09', 3, SYSDATE, 'PARESH', NULL, NULL, NULL);

INSERT INTO MENUMAS (MENUCD, MENUNM, MENUGROUP, INSERTABLE, UPDATEABLE, DELETEABLE, ORDMENU, ORDGROUP, EDATE, EUSER, WEBMENU, PAGENM, MENUNM_LABEL)
VALUES ('C.C10', 'FORM NO. 12BA', 'REPORT', 'N', 'N', 'N', 'C09', 3, SYSDATE, 'PARESH', NULL, NULL, NULL);

INSERT INTO MENUMAS (MENUCD, MENUNM, MENUGROUP, INSERTABLE, UPDATEABLE, DELETEABLE, ORDMENU, ORDGROUP, EDATE, EUSER, WEBMENU, PAGENM, MENUNM_LABEL)
VALUES ('C.C11', 'FORM NO. 24Q', 'REPORT', 'N', 'N', 'N', 'C11', 3, SYSDATE, 'PARESH', NULL, NULL, NULL);


--## UTILITY

INSERT INTO MENUMAS (MENUCD, MENUNM, MENUGROUP, INSERTABLE, UPDATEABLE, DELETEABLE, ORDMENU, ORDGROUP, EDATE, EUSER, WEBMENU, PAGENM, MENUNM_LABEL)
VALUES ('F.F01', 'BACKUP', 'UTILITY', 'Y', 'Y', 'Y', 'F01', 6, SYSDATE, 'PARESH', NULL, NULL, NULL);

INSERT INTO MENUMAS (MENUCD, MENUNM, MENUGROUP, INSERTABLE, UPDATEABLE, DELETEABLE, ORDMENU, ORDGROUP, EDATE, EUSER, WEBMENU, PAGENM, MENUNM_LABEL)
VALUES ('F.F02', 'PASSWORD CHANGE', 'UTILITY', 'Y', 'Y', 'Y', 'F02', 6, SYSDATE, 'PARESH', NULL, NULL, NULL);

INSERT INTO MENUMAS (MENUCD, MENUNM, MENUGROUP, INSERTABLE, UPDATEABLE, DELETEABLE, ORDMENU, ORDGROUP, EDATE, EUSER, WEBMENU, PAGENM, MENUNM_LABEL)
VALUES ('F.F03', 'KILL LOCKED SESSION', 'UTILITY', 'Y', 'Y', 'Y', 'F03', 6, SYSDATE, 'PARESH', NULL, NULL, NULL);

