----------------------------------------------------------------------------------------------------
-- 01/12/2024
-- PAYROLL - QUERIES
----------------------------------------------------------------------------------------------------

--#
1. ALLOWANCES KAYA KAYA RAKHVANA CHHE ?

	HAMNA ME BASIC ALLOWANCE RAKHYA CHHE..
	EX: BASIC,DA(DEARNESS),HRA(HOUSE RENT),EDUCATION(EA),TRANSPORT(TA) 
	
	ANI SIVAY KOI BIJA ADD KARVANA CHHE ?
	LIKE MEDICAL, ENTERTAINMENT ?
	
	
	
2. PF SYSTEM ?
	IF YES THEN IGNORE LIMIT RAKHVANI CHHE ?
	KE GOVT. NA RULES PRAMANE CUT KARVANU CHHE ?
	PLEASE GIVE CRITERIA AND LIMITATION.
	
	EMP PF% AND COMPANY PF% ?
	PF LIMIT AMOUNT ?
	
	
	
3. ESIC SYSTEM ?
	PLEASE EXPLAIN CRITERIA AND LIMITATION ?
	
	EMP ESIC% AND COMPANY ESIC%?
	ESIC LIMIT AMOUNT ?
	
	
4. PROFESSIONAL TAX (PT)?
	YES/NO ?
	SENIOR CITIZEN DEDUCT CRITERIA -
	

5. LABOUR WELFARE FUND SYSTEM ?

	JO RAKHVANI HOY TO CALCULATION EXPLAIN KARJO
	KAYA MONTH MA CUT THASE NE YEAR MA KETLI VAR CUT THASE ?
	COMPANY NO PART KETLO RAHSE ?
	

6. LEAVE CALCUALTION - (AFTER SALARY CREATION)
	PLEASE EXPLAIN SYSTEM
	
7. BONUS CALCUALTION - (AFTER SALARY CREATION)
	PLEASE EXPLAIN SYSTEM
	
8. FORM16 ? (AFTER SALARY CREATION)	

9. FINANCIAL YEAR ? OR TRANSFER EXISTING EMPLOYEE TO NEW COMPANY?
	YEAR CHANGE THAY TYARE EMP CLOSE THASE KE NEW FINANCIAL YEAR CREATE KARSO ?

10. TDS IN SALARY TRANSACTIO  ?
	EXPLAIN TDS CALCULATION-
	

--##
REPORTS REQUIREMENT (AFTER MODULE COMPLETED)
PRIORITY WISE REPORT NU LIST MOKALJO..

